### PR TITLE
Update CONTRIBUTING.MD

### PR DESCRIPTION
**Pull request by BenjaminSoelberg**
Added missing contributer

### CODE REVIEW

**Comment by mborgbrant** [comment]
So what is your contribution? :)

**Comment by BenjaminSoelberg** [comment]
Pull request #4 :-)

Thank you for such a great emulator.

**Comment by mborgbrant** [comment]
Oh! Sorry Benjamin. I mixed you up with someone else. Of course! Thanks for your contribution :)

**Comment by BenjaminSoelberg** [comment]
Thank you

**Pull request merged**
